### ISSUE TITLE
Jokers

### ISSUE THREAD

**Issue by bachman75** [deck-of-cards/deck-of-cards#54]
I love the app but _please_ add Jokers back into the new version.  Thank you!

**Comment by pakastin** [comment]
Soon! 😎

**Comment by vale1vale** [comment]
any update on the jokers? It would be great, to have it at this time, cause of the pandemic.

**Comment by pakastin** [comment]
Haha yeah, good point! 🤡

Previous version has those, but it’s missing multiplayer..

Juha

Sent from my iPhone

**Comment by pakastin** [comment]
I'm creating new graphics prerender tool here:
https://github.com/deck-of-cards/generate-cards

So jokers are coming very soon.........

<img width="1270" alt="Näyttökuva 2020-3-31 kello 22 19 03" src="https://user-images.githubusercontent.com/1475902/78066456-a562d980-739d-11ea-867c-b53f58ace12e.png">

**Comment by pakastin** [comment]
Jokers are added! 😎
