### ISSUE TITLE
SVG only cards - https://cardmeister.github.io/

### ISSUE THREAD

**Issue by Danny-Engelman** [deck-of-cards/deck-of-cards#60]
I am not sure if I mentioned this in this Repo before.

Last year I re-worked all 52 SVG cards into a 16KB* Custom Element/WebComponent : https://cardmeister.github.io/

I only did the graphics for 52 cards; did not do any card-game logic, no Joker either.

Deck-of-cards:
![image](https://user-images.githubusercontent.com/3382713/78059868-e998ae80-738a-11ea-8e28-10a91e45cc87.png)

with a lot of HTML/SVG/PNG

becomes:
![image](https://user-images.githubusercontent.com/3382713/78059952-0af99a80-738b-11ea-8687-8454c815f271.png)

with one HTML tag: ``<card-t cid="Jd"></card-t>`` (*generating a lot of SVG into an IMG*)

* 16 KB in the *I-cheated-version*, full version is 64KB for **all** 52 cards

https://cardmeister.github.io/

Using the Custom Elements API, so no IE support out-of-the-box (polyfill should work)

But the technique doesn't strictly require Custom Elements. It is all about generating SVG and using that  in a IMG tag.

**Comment by pakastin** [comment]
Looking good! I'm actually creating a generator with puppeteer, which can be used for creating other decks as well..

**Comment by pakastin** [comment]
Prerender tool is building up here: https://github.com/deck-of-cards/generate-cards
