### ISSUE TITLE
Multiplayer: Everyone can see all cards, Any future release on this ?

### ISSUE THREAD

**Issue by maheshsetti** [deck-of-cards/deck-of-cards#63]

**Comment by pakastin** [comment]
There’s ”bases” on top, right, bottom and left, where players can only see their own cards..

**Comment by maheshsetti** [comment]
I have a screenshot here, where we both can see other cards.

http://prntscr.com/s1tg1r

**Comment by i2y4n** [comment]
@maheshsetti 
All of the cards within the rectangle simulate a real life card table. Everyone can see those cards. If you move a card to a player (you have to drag the card over the symbol of the person) it moves into their "hand" and only that player can see the cards.

It's a little finicky, but it's a bit easier once you get the hang of it.

**Comment by pakastin** [comment]
I’ll enhance that soon! 😎
